apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants-backend
  labels:
    app: merchants-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      service: merchants-backend
  template:
    metadata:
      labels:
        app: merchants-webapi
        service: merchants-backend
    spec:
      containers:
        - name: merchants-webapi-container
          image: merchants-backend:latest
          imagePullPolicy: Never  # or IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: merchants-webapi-service
  labels:
    app: merchants-webapi
    service: merchants-backend
spec:
  type: NodePort
  ports:
    - targetPort : 80
      port: 80
      nodePort: 30008
      protocol: TCP
  selector:
    app: merchants-webapi
    service: merchants-backend